### ISSUE TITLE
Keyboard Shortcut?

### ISSUE THREAD

**Issue by mehrdd** [Collective-Software/ClickPaste#1]
Hi,
i wanted to say thank you!
I have lots of passphrases which i'm using in very specific environments (like VM in a browser tab in another VM via RDP) and the only way is typing the damn 32 complicated chars passphrases each time!
It's working great.

Just one note.. is there anyway we could use a keyboard shortcut and not pointing mouse and click on the target screen? i mean i'm already focused on the target window, so i can use a shortcut just to type the text.

Regards
Mehrdad

**Comment by ermac500** [comment]
or maybe just add a hotkey to activate program like you would by clicking the tray icon.
would speed the workload by a big margin if you don't have to activate it from the tray every time
