### ISSUE TITLE
0ms delay

### ISSUE THREAD

**Issue by replaysMike** [Collective-Software/ClickPaste#10]
Would be nice to have a 0ms delay option between keystrokes, for emulating barcode scanning input.

Otherwise, thanks for the tool ;)

**Comment by f3rrix** [comment]
It would be reasonable to have a completely configurable delay. And in general to have a settings screen where such things could live. I have stretched the context menu "UI" a bit far.

**Comment by f3rrix** [comment]
Fixed in 1.1.0
