### ISSUE TITLE
Works in Win7, but tray icon is invisible

### ISSUE THREAD

**Issue by Atario** [Collective-Software/ClickPaste#14]
What it looks like:

![](https://files.catbox.moe/e6kmn9.png)

**Comment by f3rrix** [comment]
Glad you find it useful, but I don't have any plans to work on it personally for support with Windows 7, which is itself not supported by MS any more.

**Comment by Atario** [comment]
I should add that the problem is possible in the supported versions of Windows as well.

It seems the issue is that the icon is white-on-transparent, so if the background is also white (or close to it), it disappears.  So this could happen in Win10/Win11 if you set your accent color to white (or close to it).

**Comment by f3rrix** [comment]
It's supposed to only be white when the background is dark.  It uses:

Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\SystemUsesLightTheme

to know this and flip the icon to black on transparent otherwise.
