### ISSUE TITLE
Problem with diacritics

### ISSUE THREAD

**Issue by janz1961** [Collective-Software/ClickPaste#15]
This may not be possible to fix (at least not easily).

When you use an international keyboard, there is a neat way to type characters like Ä.  You type a quote first and then the character. But, if your copy-paste buffer contains a quote, this also triggers this behavior. 

For example, I paste a piece of Powershell containing a line as this:

**"Alert: something went wrong"**

This is pastes as:

**Älert: something went wrong"**

And then something is wrong indeed. Maybe there is a way around this like (pseudo code because I wouldn't know how to do it in any language :-) ):

**#Start paste**
**savekeyboard = GetKeyboard()**
**SetKeyboard(KeyboardWithoutThisBehavior)**

**DoPaste()**

**SetKeyboard(savekeyboard)**

**Comment by f3rrix** [comment]
Open to suggestions. One possible problem I can think of is that other keyboards have other meanings for the same key codes too. It's unclear to me what the "right" approach to these things would be.
