### ISSUE TITLE
Enhancement:  config to paste without mouse

### ISSUE THREAD

**Issue by Atario** [Collective-Software/ClickPaste#16]
Per #11:

>It would be reasonable to make a configuration switch for the hotkey behavior from "turn on select mode" to "just shut up and paste right now, where the caret is"

**Comment by Frew777** [comment]
Would be useful

**Comment by Reftek85** [comment]
but it would be perfect for RDP

**Comment by f3rrix** [comment]
I'm not convinced of that, RDP tends to eat hotkeys when it's in focus.  But it's still a fine idea to implement regardless.

**Comment by Reftek85** [comment]
My main issue with RDP is that the pasting process starts at the first click of the mouse after activation, but i need to double click, first click to focus on RDP window, and second click to select the input field ex: logon password input field. That cause the first chars to not be pasted at the destination. it would need a pasting delay option.
https://github.com/Collective-Software/ClickPaste/issues/22#issue-2261893627
