### ISSUE TITLE
Slow Down Typing

### ISSUE THREAD

**Issue by ddrinka** [Collective-Software/ClickPaste#2]
When sending keystrokes to some web-based remote management apps, the default 5ms delay per keystroke in AutoIt overruns the buffer and the pasted text is corrupted.

It'd be great to have a configurable per keystroke delay to slow down typing for my use case.

https://documentation.help/AutoItX/AutoItSetOption.htm#SendKeyDelay

**Comment by f3rrix** [comment]
Great idea

**Comment by stephendt** [comment]
Just logged in to mention this is an issue for me as well. A missed keystroke can be pretty frustrating at times. A configurable typing speed would be great.

**Comment by f3rrix** [comment]
To anyone watching the issue: is it a problem for SendKeys mode, or only in AutoIt_Send?

**Comment by f3rrix** [comment]
Added in v1.0.1
