### ISSUE TITLE
Feature request - Indication for when pasting

### ISSUE THREAD

**Issue by nOrphf** [Collective-Software/ClickPaste#21]
Hi

Much of my ClickPaste use is passwords into password boxes. Password for service accounts has gotten long for at least some of my customers, but the password field is small. 
Therefore, when I paste a long password into a password field (Easily 32 characters) I can't see when it's done as I can't see the "dots" move.
Besides it's a long password, for ClickPaste to work correctly through Remote desktop I have set wait time to 40 milli so it takes longer to type than the default wait time.

So if, for instance, the system tray icon could turn red (or green) when typing I can look when it goes back to white and I know when it is done.

Regards Lars

P.s. Awsome program!!!

**Comment by f3rrix** [comment]
That's a great idea
