### ISSUE TITLE
Enhancement: Configurable delay before start typing

### ISSUE THREAD

**Issue by Reftek85** [Collective-Software/ClickPaste#22]
When launching clickpaste, I need to double click in the password field on the windows login screen that is an RDP session

the copy paste process seems to start at the very first click before the second clicks select the password box on the logon screen.

there is a delay between chars, but is there a way to add a delay before the copy process starts? I tried to look in the ClickPaste.config file I see nothing for a pasting delay.

**Comment by f3rrix** [comment]
Nothing exists like that now, but adding a delay is a good feature suggestion
