### ISSUE TITLE
Cannot change typing method to Forms.SendKeys

### ISSUE THREAD

**Issue by DBartelds** [Collective-Software/ClickPaste#24]
Whenever I click "Done" in the settings menu, the Typing Method settings goes to AutoIt.Send.
Even when I manually edit the user.config XML file in the AppData\Local folder and set the value of the TypeMethod setting to 0, start the application and open the Settings window, the radio button for Forms.SendKeys is selected, but when I click Done _without changing any setting_ the value in the XML file is set to 1 and the settings window will show "AutoIt.Send" as selected again the next time I open the settings window.

**Comment by f3rrix** [comment]
I don't know what to do with this one, as it doesn't seem to happen for me. Is everyone else seeing the problem too? Maybe we can figure out what's different.

**Comment by f3rrix** [comment]
Discovered there was a 1 byte difference between the version I've been using and the actual release. Committed as 1.2.0 so hopefully that unborks everyone's typing methods.

**Comment by DBartelds** [comment]
@f3rrix 👍 Thank you
