### ISSUE TITLE
RDP: special characters broken

### ISSUE THREAD

**Issue by fansari** [Collective-Software/ClickPaste#26]
I thought this tool might be useful to enter passwords to the console for vSphere.

Unfortunately special characters (punctation, parenthesis, ...) are broken.

I tested on a vSphere console and also pasting into notepad on the RDP server.

**Comment by f3rrix** [comment]
Could it be a keyboard mode thing?  The key sending APIs we rely upon basically disclaim any support for anything but US key layouts.

**Comment by ewscott9** [comment]
I've had a similar issue in RDP, and changing the delay between helped (I think I bumped to up to 100 ms or so). I think rdp was eating the shift inputs.

**Comment by fansari** [comment]
I got it working last week. In this case my notebook keyboard settings and the keyboad on the RDP server both were US. Maybe when I had the issue I had tried to set everything to US after I noticed the problem and it seems that this does not work.

**Comment by f3rrix** [comment]
Can you try with different delays and switching typing method?  (v1.2.0 fixes hopefully a bug that prevented typing method switching)

**Comment by gs71** [comment]
I confirm that ClickPaste is not working properly when using a French keyboard : all characters that need AltGr (~{ [ | ] } .... ) are not pasted at all.
But it works fine if I select US keyboard layout just before pasting.

Do you think this issue could be fixed? ClickPaste is a great tool apart from this problem!

**Comment by f3rrix** [comment]
Ah.  Alas no, unless someone comes up with a new way to type keys.  Both AutoIt and Forms.SendKeys explicitly disclaim support for anything but US keyboards.
