### ISSUE TITLE
Some characters removed

### ISSUE THREAD

**Issue by Melog01** [Collective-Software/ClickPaste#3]
HI, 
it is great tool. I am using it to paste some coding in citrix remote connection, where copy pate is blocked.
Unfortunately some characters used in my code are removed. 
They are "@" and "#" as I found until now. Is it possible to change the code to paste also these characters ?

Thank you

**Comment by f3rrix** [comment]
I don't use Citrix, but these characters paste just fine when I try it in other apps, including to VMware guest machines.  I'm not sure what I can do to produce the problem.  Did you try switching key typing method between sendkeys and autoit?

**Comment by Melog01** [comment]
Yes, I did try both methods. I have no other choice. I have no other choice. I am only user which have to use it. The Citrix connection is running in web browser as Citrix. lite. Other characters like %, ', " etc. are working fine. You are right, in case I am pasting to local text editor, it is working fine and all characters are there. May be some timing issue with the remote connection and key press simulation. Now I have some idea. As I am using swiss keyboard layout, these not working characters are with AltGr+some other key. This can be issue also with other layouts, where special characters are accessible with AltGr modifier. Working characters as % are only with Shift key.

**Comment by Melog01** [comment]
Now I changed keyboard layout ti English and it is working. All characters are there. So definitely it is related to the AltGr key necessity for some characters.

**Comment by Melog01** [comment]
Do you plan to solve that issue with different keyboard ?

**Comment by f3rrix** [comment]
I'm not sure how that issue could be addressed.  The "Send keys" functions don't have a lot of options and I suspect that is where the limitation is.

For example [Microsoft says](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.sendkeys.send?view=net-5.0):

> If your application is intended for international use with a variety of keyboards, the use of Send could yield unpredictable results and should be avoided.

Which basically equals "we know this won't work, and we don't care" :(
