### ISSUE TITLE
Messed up when blocked by apps

### ISSUE THREAD

**Issue by JakeQZ** [Collective-Software/ClickPaste#4]
In these troubling times, it is not surprising that people want to translate a message into Russian (or Ukranian) and paste it into the chat.  Perhaps while playing poker and finding some Russian players at the table.

[Application name redacted] seems to have found a way to prevent ClickPaste from pasting into the chat box (there have been almost daily updates to their client app in the last fortnight; though their Windows client seems not to support Unicode anyway, so I don't know if non-ASCII characters would even appear correctly for users with a different Windows system locale for legacy apps).  I was able to use ClickPaste with [app] chat a couple of weeks ago (with non-ASCII characters echoed as garbage my end), but can no longer do so.

The bug in ClickPaste is that when an app employs whatever defence it is using, the target cursor remains active, and it does not seem possible to cancel it.  Eventually clicking on an unintended window can cause the keystrokes to be sent in such a way as to invoke menu items and wreak all sorts of havoc.

I tried pressing Esc to cancel but that did not work.

(Incidentally, it seems that [app] has now blocked Russian-registered accounts from playing.)

**Comment by f3rrix** [comment]
Oh yeah, I intend to make a way to ESCape the target.  I have run into this as well :)

**Comment by JakeQZ** [comment]
Oddly I tried changing the typing method (to Forms_SendKeys), and pasting into [redacted site] worked.  Then I changed it back (to AutoIt_Send), and it still worked.  So I don't really know what the issue was with the [redacted site] not accepting the pasting at the time I created this issue.

**Comment by f3rrix** [comment]
Fixed in v1.0.1
