### ISSUE TITLE
Teamviewer

### ISSUE THREAD

**Issue by KAURkulaator** [Collective-Software/ClickPaste#5]
Can't use with Teamviewer.
Here is a video. I have a different color mouse on my local computer and the TV computer has the regular color.
https://user-images.githubusercontent.com/89666207/195864780-7c3db0fe-238e-42de-b3f9-39dad32df4ec.mp4

**Comment by f3rrix** [comment]
It works fine with teamviewer for me.  Did you launch TV as another context (Run as Administrator) but clickpaste only as a normal user?

**Comment by KAURkulaator** [comment]
Hi, thanks for the fast replay, it would seem that Teamviewer was running as admin and ClickView not...
Didn't think about that at all.
