### ISSUE TITLE
Keys changing format when pasting

### ISSUE THREAD

**Issue by Farmand77** [Collective-Software/ClickPaste#9]
Im trying to paste a longer string containing this part here using autoit send
"k^oU:|y&b
this is the result its combining two keys
"kôU:|y&b
When using forms sendkeys
w"k&oU:|y&b
both options creates a"typo"
Im on windows danish keyboard but changing to english does not help.

**Comment by f3rrix** [comment]
This doesn't happen on mine, it seems like you have some software trying to help you type accented characters? Such that when you say ^ followed by o it emits ô?

**Comment by dor73** [comment]
> This doesn't happen on mine, it seems like you have some software trying to help you type accented characters? Such that when you say ^ followed by o it emits ô?

thanks for your help. I've solved disabling autocorrect misspelled words in Windows 10. Now it also works with VMWare Remote Console
